[tool.poetry]
name = "threatx-api-client"
version = "1.0.0"
description = "A client library for the ThreatX API"
authors = ["Nikita Ratskov <nikita.ratskov@threatx.com>"]
license = ""
readme = "README.md"
packages = [{include = "threatx_api_client"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.288"
coverage = "^7.3.1"

[tool.poetry.group.release.dependencies]
python-semantic-release = "^8.0.8"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
major_on_zero = false
branch = "main"
upload_to_vcs_release = true
