[tool.poetry]
name = "threatx-api-client"
version = "1.0.0"
description = "A client library for the ThreatX API"
authors = ["Nikita Ratskov <nikita.ratskov@threatx.com>"]
license = ""
readme = "README.md"
packages = [{include = "txapiclient"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.288"
coverage = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
