# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/**"
      - "threatx_api_client/**"
      - "tests/**"
      - "./**.toml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/**"
      - "threatx_api_client/**"
      - "tests/**"
      - "./**.toml"

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Running pytest
        run: poetry run pytest
        env:
          TX_API_PROD_KEY: ${{ secrets.TX_API_PROD_KEY }}
          TX_API_POD_KEY: ${{ secrets.TX_API_POD_KEY }}

  release:
    needs: test
    runs-on: ubuntu-latest
    concurrency: release
    permissions: write-all
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Build wheel package
        shell: bash
        run: poetry build --format wheel

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: threatx-api-client
