name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Ruff check
        run: poetry run ruff check

      - name: Pytest
        run: poetry run pytest
        env:
          TX_API_PROD_KEY: ${{ secrets.TX_API_PROD_KEY }}
          TX_API_POD_KEY: ${{ secrets.TX_API_POD_KEY }}
          TX_API_TEST_TENANT: ${{ secrets.TX_API_TEST_TENANT }}

      - name: Build Python WHL package
        run: poetry build -f wheel

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./dist/*.whl
          file_glob: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
