name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "threatx_api_client/**"
      - "tests/**"
  push:
    branches:
      - main
    paths:
      - "threatx_api_client/**"
      - "tests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Ruff check
        run: poetry run ruff check

      - name: Pytest
        run: poetry run pytest
        env:
          TX_API_PROD_KEY: ${{ secrets.TX_API_PROD_KEY }}
          TX_API_POD_KEY: ${{ secrets.TX_API_POD_KEY }}
          TX_API_TEST_TENANT: ${{ secrets.TX_API_TEST_TENANT }}

  results:
    name: Test results
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          result="${{ needs.test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi