name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files: |
            threatx_api_client/**
            tests/**

  test:
    name: Test
    needs: get-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.matrix != '[]' }}
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Ruff check
        run: poetry run ruff check

      - name: Pytest
        run: poetry run pytest
        env:
          TX_API_PROD_KEY: ${{ secrets.TX_API_PROD_KEY }}
          TX_API_POD_KEY: ${{ secrets.TX_API_POD_KEY }}
          TX_API_TEST_TENANT: ${{ secrets.TX_API_TEST_TENANT }}

  results:
    name: Test results
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    steps:
      - run: |
          result="${{ needs.test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi